print("")
print("")
print("")
print("")
print("")
print("  ___                              _                                     ")
print(" | _ \__ _ _______ __ _____ _ _ __| |  _ __  __ _ _ _  __ _ __ _ ___ _ _ ")
print(" |  _/ _` (_-<_-< V  V / _ \ '_/ _` | | '  \/ _` | ' \/ _` / _` / -_) '_|")
print(" |_| \__,_/__/__/\_/\_/\___/_| \__,_| |_|_|_\__,_|_||_\__,_\__, \___|_|  ")
print("                                                           |___/         ")
print("")
print("Enter account type: ")
print("")
print("")
print("")
print("")
print("")
